# cluster.yaml

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: todo-cluster
  region: ap-south-1

vpc:
  id: vpc-053b5bc785fa1ccf3
  subnets:
    private:
      ap-south-1a:
        id: subnet-0adb4255efc10d129
      ap-south-1b:
        id: subnet-0e137b17de0311269
  nat:
       gateway: HighlyAvailable

managedNodeGroups:
  - name: todo-nodes
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    privateNetworking: true
    subnets:
      - subnet-0adb4255efc10d129
      - subnet-0e137b17de0311269
