apiVersion: v1
kind: Secret
metadata:
    name: todo-secret
    namespace: default
type: Opaque
data:
  DB_USER: YWRtaW4=
  DB_PASSWORD: UmFpY2h1MTgwOA== 
  JWT_SECRET: eW91cl9zdXBlcl9zZWNyZXRfand0X2tleV9jaGFuZ2VfaW5fcHJvZHVjdGlvbl8xMjM0NQ==
