apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: todo-frontend
spec:
  type: LoadBalancer
  selector:
    app: todo-frontend
  ports:
    - name: http
      protocol: TCP
      port: 80        # External LB port
      targetPort: 3000 # Container port

